
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID NUM PD PE VIRG\n    lista_mista : PE conteudo PD\n\n    conteudo :\n              | elementos\n\n    elementos : elemento\n              | elemento VIRG elementos\n\n    elemento : ID\n             | NUM\n             |       \n    '
    
_lr_action_items = {'PE':([0,],[2,]),'$end':([1,8,],[0,-1,]),'PD':([2,3,4,5,6,7,9,10,],[-2,8,-3,-4,-6,-7,-8,-5,]),'ID':([2,9,],[6,6,]),'NUM':([2,9,],[7,7,]),'VIRG':([2,5,6,7,9,],[-8,9,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lista_mista':([0,],[1,]),'conteudo':([2,],[3,]),'elementos':([2,9,],[4,10,]),'elemento':([2,9,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lista_mista","S'",1,None,None,None),
  ('lista_mista -> PE conteudo PD','lista_mista',3,'p_grammar','lmistas.py',33),
  ('conteudo -> <empty>','conteudo',0,'p_grammar','lmistas.py',35),
  ('conteudo -> elementos','conteudo',1,'p_grammar','lmistas.py',36),
  ('elementos -> elemento','elementos',1,'p_grammar','lmistas.py',38),
  ('elementos -> elemento VIRG elementos','elementos',3,'p_grammar','lmistas.py',39),
  ('elemento -> ID','elemento',1,'p_grammar','lmistas.py',41),
  ('elemento -> NUM','elemento',1,'p_grammar','lmistas.py',42),
  ('elemento -> <empty>','elemento',0,'p_grammar','lmistas.py',43),
]
